# Generated by Django 2.2.8 on 2020-01-07 22:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_pages', '0005_auto_20200107_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='body',
            field=wagtail.fields.StreamField(
                [('paragraph', wagtail.blocks.RichTextBlock()),
                 ('image', wagtail.images.blocks.ImageChooserBlock()),
                 ('Html', wagtail.blocks.RawHTMLBlock()),
                 ('Embed', wagtail.blocks.RawHTMLBlock())],
                blank=True),
        ),
    ]
