# Generated by Django 4.2.5 on 2023-09-17 15:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_pages", "0006_auto_20200107_2252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helppage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("Html", wagtail.blocks.RawHTMLBlock()),
                    ("Embed", wagtail.blocks.RawHTMLBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
