# Generated by Django 2.2.7 on 2019-11-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191126_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True,
                                   error_messages={
                                       'invalid': 'غلط',
                                       'required': 'الرجاء تعبئة هذا الحقل'
                                   },
                                   help_text='hoon',
                                   max_length=200,
                                   null=True,
                                   unique=True),
        ),
    ]
