# Generated by Django 2.2.7 on 2019-11-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
