# Generated by Django 2.2.7 on 2019-11-26 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191126_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True,
                                    max_length=254,
                                    null=True,
                                    unique=True,
                                    validators=[
                                        django.core.validators.EmailValidator(
                                            message='your custom message')
                                    ]),
        ),
    ]
