# Generated by Django 2.2.7 on 2019-11-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_tools_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.IntegerField(default=16),
        ),
    ]
