# Generated by Django 2.2.7 on 2019-11-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('DEFAULT', 'الإفتراضي'),
                                            ('BABA', 'واضح'),
                                            ('MODERN', 'حديث')],
                                   default='DEFAULT',
                                   max_length=10),
        ),
    ]
