# Generated by Django 2.2.7 on 2019-11-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191127_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='main.Person'),
        ),
    ]
