# Generated by Django 2.2.7 on 2019-11-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_user_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(to='main.Person'),
        ),
    ]
