# Generated by Django 2.2.7 on 2019-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191129_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='history',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='person',
            name='designation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
