# Generated by Django 2.2.8 on 2020-01-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_merge_20191208_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmark',
        ),
    ]
