# Generated by Django 2.2.8 on 2020-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_user_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(max_length=150,
                                   null=True,
                                   verbose_name='مكان الولادة'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(max_length=150,
                                   null=True,
                                   verbose_name='اسم الأب'),
        ),
        migrations.AddField(
            model_name='user',
            name='grandfather_name',
            field=models.CharField(max_length=150,
                                   null=True,
                                   verbose_name='اسم الجد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='تاريخ الميلاد'),
        ),
    ]
