# Generated by Django 4.2.5 on 2023-09-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_remove_user_theme_alter_user_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="font_size",
        ),
    ]
