# Generated by Django 4.2.5 on 2023-09-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_remove_user_font_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tools_toggle",
        ),
    ]
