# Generated by Django 4.2.5 on 2023-09-17 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_remove_user_tools_toggle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="designation",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Designation (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="editor",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Editor"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="history",
            field=models.CharField(
                blank=True,
                max_length=2000,
                verbose_name="Historical Background (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.person",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="reference",
            field=models.CharField(
                blank=True,
                max_length=1000,
                verbose_name="Reference of authentication (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Enter a valid email address"
                    )
                ],
            ),
        ),
    ]
