# Generated by Django 4.2.5 on 2023-09-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_person_designation_alter_person_editor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="main.person",
                verbose_name="Parent",
            ),
        ),
    ]
