# Generated by Django 4.2.5 on 2023-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_person_creation_time_person_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="designation",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Designation (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="history",
            field=models.TextField(
                blank=True,
                max_length=2000,
                verbose_name="Historical Background (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="reference",
            field=models.TextField(
                blank=True,
                max_length=1000,
                verbose_name="Reference of authentication (optional)",
            ),
        ),
    ]
