# Generated by Django 6.0.6 on 2026-06-11 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Email verification'), ('password_reset', 'Password reset')], default='activation', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='emailverification',
            constraint=models.UniqueConstraint(fields=('user', 'purpose'), name='unique_user_purpose_code'),
        ),
    ]
