# Generated by Django 2.2.8 on 2020-01-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0022_merge_20191208_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('x', models.IntegerField(default=0,
                                          verbose_name='إحداثي سيني')),
                ('y', models.IntegerField(default=0,
                                          verbose_name='إحداثي صادي')),
                ('person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='main.Person')),
            ],
        ),
    ]
