# Generated by Django 4.2.5 on 2023-09-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["person__pk"]},
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="x",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="y",
        ),
    ]
