# Generated by Django 4.2.5 on 2023-09-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_rename_editor_person_editors"),
        ("home", "0003_bookmark_color_bookmark_font_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="label",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Label"
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="color",
            field=models.CharField(
                blank=True, default=None, max_length=6, null=True, verbose_name="Color"
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="font_color",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=6,
                null=True,
                verbose_name="Font Color",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="font_size",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Font Size"
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.person",
                verbose_name="Person",
            ),
        ),
    ]
