# Generated by Django 6.0.6 on 2026-06-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tag_parent'),
        ('main', '0033_alter_person_designation_alter_person_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_person', models.ForeignKey(blank=True, help_text='The bookmarked person shown at the center of the home tree. Leave empty for the default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.person', verbose_name='Home center person')),
            ],
        ),
    ]
