# Generated by Django 6.0.6 on 2026-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='node_max_scale',
            field=models.FloatField(default=1.2, help_text='Visual size multiplier for nodes at the root of the tree.', verbose_name='Max node scale'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='node_min_scale',
            field=models.FloatField(default=0.5, help_text='Visual size multiplier for the deepest (leaf) nodes.', verbose_name='Min node scale'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='node_size_decay',
            field=models.FloatField(default=0.15, help_text='How quickly node size shrinks per generation away from the root. Higher values shrink faster; 0 makes all nodes the same size.', verbose_name='Node size decay'),
        ),
    ]
