# Generated by Django 6.0.6 on 2026-06-10 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homesettings_node_max_scale_and_more'),
        ('main', '0033_alter_person_designation_alter_person_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='tag',
            name='font_color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Font Color'),
        ),
        migrations.AddField(
            model_name='tag',
            name='font_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Font Size'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_bookmark',
            field=models.ForeignKey(blank=True, help_text='A bookmarked person this tag should appear under, instead of another tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tags', to='main.person', verbose_name='Parent bookmark'),
        ),
    ]
