# Generated by Django 6.0.6 on 2026-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tag_color_tag_font_color_tag_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='node_padding',
            field=models.FloatField(default=8.0, help_text='Gap (in logical pixels) kept between a node and its parent/siblings when packing the home tree. 0 packs nodes edge-to-edge.', verbose_name='Cluster spacing'),
        ),
    ]
