# Generated by Django 6.0.6 on 2026-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homesettings_node_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='node_edge_factor',
            field=models.FloatField(default=2.0, help_text='Caps how far a child sits from its parent, as a multiple of the minimum spacing. Lower values shorten edges; when hit, the fan widens instead.', verbose_name='Max edge length'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='node_spread_degrees',
            field=models.FloatField(default=160.0, help_text='Preferred breadth (in degrees) of the fan a node spreads its children over. Wider angles give shorter edges when a node has many children.', verbose_name='Spread angle'),
        ),
    ]
