# Generated by Django 6.0.6 on 2026-06-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homesettings_node_edge_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='root_color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Root color'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='root_font_color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Root font color'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='root_font_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Root font size'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='root_label',
            field=models.CharField(blank=True, default=None, help_text='Text shown on the central root node. Leave empty to show the default tree icon.', max_length=200, null=True, verbose_name='Root label'),
        ),
    ]
