# Generated by Django 2.2.8 on 2020-01-07 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore',
         '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtail_pages', '0002_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutPage',
        ),
    ]
