# Generated by Django 2.2.8 on 2020-01-07 21:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_pages', '0004_helppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='body',
            field=wagtail.fields.StreamField([
                ('heading', wagtail.blocks.CharBlock(classname='full title')),
                ('paragraph', wagtail.blocks.RichTextBlock()),
                ('image', wagtail.images.blocks.ImageChooserBlock())
            ]),
        ),
    ]
