# Generated by Django 4.2.5 on 2023-10-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_pages", "0007_alter_helppage_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
