# Generated by Django 2.2.7 on 2019-11-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('DEFAULT', 'الإفتراضي'),
                                            ('BABA', 'الواضح'),
                                            ('MODERN', 'الحديث')],
                                   default='DEFAULT',
                                   max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='tools_toggle',
            field=models.CharField(default='inline', max_length=20),
        ),
    ]
