# Generated by Django 2.2.7 on 2019-12-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20191129_1852'),
        ('main', '0021_auto_20191129_1853'),
    ]

    operations = []
