# Generated by Django 4.2.5 on 2023-09-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_alter_person_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="editor",
            new_name="editors",
        ),
    ]
