# Generated by Django 2.2.7 on 2019-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191126_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(blank=True,
                                    max_length=254,
                                    null=True,
                                    unique=True),
        ),
    ]
