# Generated by Django 2.2.7 on 2019-11-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email2',
        ),
    ]
