# Generated by Django 2.2.7 on 2019-11-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191126_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tools_toggle',
            field=models.BooleanField(default=True),
        ),
    ]
