# Generated by Django 4.2.5 on 2023-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_bookmark_options_remove_bookmark_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="font_color",
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="font_size",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
